spring.application.name=atsanalyzer

server.port=${PORT:8080}

# ==========================
# OpenRouter
# ==========================
openrouter.api.key=${OPENROUTER_API_KEY}

# ==========================
# MySQL Configuration
# ==========================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# ==========================
# JPA / Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect